doctrine:
    dbal:
        # Ensure any URL-special characters in username or password are encoded
        # in the env var so that `resolve:` works.
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '12.8'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Outlandish\Wpackagist\Entity:
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                is_bundle: false
                prefix: Outlandish\Wpackagist\Entity
                alias: App
