version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.2.1

workflows:
  deploy-staging:
    jobs:
      - aws-ecr/build-and-push-image:
          context:
            - ecs-deploys
          filters:
            branches:
              only:
                - develop
          repo: 'staging-wpackagist'
          region: AWS_REGION
          tag: 'staging,staging-${CIRCLE_SHA1}'
          extra-build-args: '--build-arg env=stg'
      - aws-ecs/deploy-service-update:
          context:
            - ecs-deploys
          requires:
            - aws-ecr/build-and-push-image
          aws-region: AWS_REGION
          family: 'ol-ecs-staging-wpackagist'
          cluster-name: 'ol-ecs-staging-shared'
          service-name: 'staging-wpackagist'

  deploy-production:
    jobs:
      - aws-ecr/build-and-push-image:
          context:
            - ecs-deploys
          filters:
            branches:
              only:
                - main
          repo: 'production-wpackagist'
          region: AWS_REGION
          tag: 'production,production-${CIRCLE_SHA1}'
          extra-build-args: '--build-arg env=prod'
      - aws-ecs/deploy-service-update:
          context:
            - ecs-deploys
          requires:
            - aws-ecr/build-and-push-image
          aws-region: AWS_REGION
          family: 'ol-ecs-production-wpackagist'
          cluster-name: 'ol-ecs-production-shared'
          service-name: 'production-wpackagist'
